import React from 'react' 
export default function PrivacyPolicy() {
  return (
    <div style={{color:"grey",fontSize:"12px"}} className='ml-20 mt-20 mb-20 text-15px text-grey'>
      <p style={{fontWeight:"bold", color:"black",marginLeft:"180PX",fontSize:"14px"}}>PRIVACY POLICY</p>
  <p style={{fontWeight:"bold", color:"black",marginLeft:"50PX",fontSize:"14px"}}>GOSWIFTPE TECHNOLOGIES PRIVATE LIMITED (Crosspe)</p>
  <p style={{color:"black",marginLeft:"150PX"}}>Last Updated - 26-Jul-2022</p>
  <p>1. Introduction</p>
  <p>Welcome to GOSWIFTPE TECHNOLOGIES PRIVATE LIMITED.</p>
  <p>GOSWIFTPE TECHNOLOGIES PRIVATE LIMITED.(“us”, “we”, or “our”) operates</p>
  <p>https://gocrosspe.com and the services on Crosspe platform. (hereinafter referred to as <br/>“Service”).</p>
  <p>Our Privacy Policy governs your visit to https://gocrosspe.com and partner sites and</p>
  <p>applications operated by us and the services we provide on the platform, and</p>
  <p>explains how we collect, safeguard and disclose information that results from your</p>
  <p>use of our Service.</p>
  <p>We use your data to provide and improve Service. By using Service, you agree to</p>
   <p>the collection and use of information in accordance with this policy. Unless</p>
   <p>otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have</p>
    <p>the same meanings as in our Terms and Conditions.</p>
    <p>Our Terms and Conditions (“Terms”) govern all use of our Service and together</p>
    <p>with the Privacy Policy constitutes your agreement with us (“agreement”).</p><br/>

      <p>2. Definitions</p>
      <p>SERVICE means the https://gocrosspe.com website operated by GOSWIFTPE TECHNOLOGIES</p>
      <p>PRIVATE LIMITED.</p>
      <div>PERSONAL DATA means data about a living individual who can be identified from <br/>
      those data (or from those and other information either in our possession or likely<br/>
      to come into our possession).<br/>
      USAGE DATA is data collected automatically either generated by the use of<br/>
      Service or from Service infrastructure itself (for example, the duration of a page<br/>
      visit).<br/>
      COOKIES are small files stored on your device (computer or mobile device).<br/>
      DATA CONTROLLER means a natural or legal person who (either alone or jointly or <br/>
      in common with other persons) determines the purposes for which and the<br/>
      manner in which any personal data are, or are to be, processed. For the purpose of<br/>
      this Privacy Policy, we are a Data Controller of your data.
      <br/>
      <br/>
      <br/>

DATA PROCESSORS (OR SERVICE PROVIDERS) means any natural or legal person<br/>
who processes the data on behalf of the Data Controller. We may use the services<br/>
of various Service Providers in order to process your data more effectively.<br/>
DATA SUBJECT is any living individual who is the subject of Personal Data.<br/>
THE USER is the individual using our Service. The User corresponds to the Data<br/>
Subject, who is the subject of Personal Data.<br/><br/>
3. Information Collection and Use<br/><br/>
We collect several different types of information for various purposes to provide<br/>
and improve our Service to you.<br/><br/><br/>
4. Types of Data CollectedPersonal Data<br/><br/>
While using our Service, we may ask you to provide us with certain personally<br/>
identifiable information that can be used to contact or identify you (“PersonalData”). <br/>
This information can be provided by you directly when you access the<br/>
platform or perform any transactions on the platform. Personally identifiable<br/>
information may include, but is not limited to:<br/>
a. Your contact information (e.g., name, email address, phone number, billing or<br/>
mailing address, age, date of birth gender, citizenship, occupation and other<br/>
relevant contact information)<br/>
b. Bank and credit account informationc. IP addressd.<br/>
 Identity validation (e.g., photograph, other information requested to verify your<br/>
 information, including copy of valid ID document)<br/>
 e. Government identification document numbers, such as Aadhaar card<br/>
 information, Pancard, passport, driving license, proof of identity (POI) <br/>
 and proof ofaddress (POA) details, etc.<br/>
 f. Publicly available and/or criminal history<br/>
 g. National identification numbers<br/>
 h. Nationality<br/>
 i. Date and place of birth<br/>
 j. Details of any transactions carried out using any the services<br/>
k. Any other information that you choose to provide to us (e.g., if you send us an<br/>
email/otherwise contact us)<br/>
l. Calls/emails/other correspondence<br/>
m. Information through Cookies and other tracking technologies as listed above<br/>
and as described in the section below entitled “Tracking Cookies Data”<br/>
You are responsible for providing accurate and up-to-date information.<br/>
If you are required to provide information about shareholders or beneficial owners<br/>
of your business, you acknowledge that you have that person’s consent to provide<br/>
his/her information to us. This may include:<br/>
a. Contact information, such as name, home address, and email address.<br/>
b. Account information, such as username and password.<br/>
c. Financial information, such as bank account numbers, bank statement, and<br/>
trading information.<br/>
d. Identity verification information, such as images of your government issued ID,<br/>
passport, national ID card, or driving license. Note: US residents may be asked to<br/>
provide their social security numbers.<br/>
e. Residence verification information, such as Utility bill details or similar<br/>
information.<br/>
We may use your Personal Data to contact you with newsletters, marketing or<br/>
promotional materials and other information that may be of interest to you. You<br/>
may opt out of receiving any, or all, of these communications from us by following<br/>
the unsubscribe link or contacting us on the available channels.<br/>
Users can always refuse to supply personally-identifying information, with the<br/>
caveat that it may prevent them from being able to use Crosspe's and its partner’s<br/>
services.<br/>
We may collect and process Personal Data about Buyers or third parties related to<br/>
your business in providing Crosspe Services. You are responsible for making sure<br/>
that the privacy rights of any third parties, including Buyers and other individuals<br/>
related to your business, are respected, including ensuring appropriated<br/>
isclosures about third party data collection and use; with respect to such data<br/>
you hereby (i) are deemed to be and (ii) accept to be controller. To the extent that<br/>
we are acting as your data processor, we will process Personal Data in accordance<br/>
with the terms of our agreement with you and your lawful instructions. <br/><br/>
Usage Data<br/>
We may also collect information that your browser sends whenever you visit our<br/>
Service or when you access Service by or through any device (“Usage Data”).<br/>
This Usage Data may include information such as your computer’s Internet<br/>
Protocol address (e.g. IP address), browser type, browser version, the pages of our<br/>
Service that you visit, the time and date of your visit, the time spent on those<br/>
pages, unique device identifiers and other diagnostic data.<br/>
When you access Service with a device, this Usage Data may include information<br/>
such as the type of device you use, your device unique ID, the IP address of your<br/>
device, your device operating system, the type of Internet browser you use,<br/>
unique device identifiers and other diagnostic data.<br/><br/>
Location Data<br/>
We may use and store information about your location if you give us permission<br/>
to do so (“Location Data”). We use this data to provide features of our Service, to<br/>
improve and customize our Service.<br/>
You can enable or disable location services when you use our Service at any time<br/>
by way of your device settings wherever applicable.<br/>
Device Information<br/>
We may collection and use computer and mobile device information, such as the<br/>
domain and host you use to access the Internet; your computer’s IP address;<br/>
mobile device geolocation, number and other information from and about your<br/>
device (such as device properties, settings, applications, stored information and<br/>
usage) and carrier; the browser and operating system software you use; websites<br/>
you have visited or later visit, social profile and network information; the date and<br/>
time you access our website, the internet address used to link to our website<br/>
when you visit us and cookie information wherever necessary to provide or<br/>
improve the services on platform.Tracking Cookies Data<br/>
We use cookies and similar tracking technologies to track the activity on our<br/>
Service and we hold certain information.<br/>
Cookies are files with a small amount of data which may include an anonymous<br/>
unique identifier. Cookies are sent to your browser from a website and stored on<br/>
your device. Other tracking technologies are also used such as beacons, tags and<br/>
scripts to collect and track information and to improve and analyze our Service.<br/><br/>
You can instruct your browser to refuse all cookies or to indicate when a cookie is<br/>
being sent. However, if you do not accept cookies, you may not be able to use<br/>
some portions of our Service.<br/><br/><br/><br/>
Examples of Cookies we use:<br/>
a. Session Cookies: We use Session Cookies to operate our Service.<br/>
b. Preference Cookies: We use Preference Cookies to remember your preferences<br/>
and various settings.<br/>
c. Security Cookies: We use Security Cookies for security purposes.<br/>
d. Advertising Cookies: Advertising Cookies are used to serve you with <br/>
advertisements that may be relevant to you and your interests.Other Data<br/>
While using our Service, we may also collect the following information: sex, age,<br/>
date of birth, place of birth, passport details, citizenship, registration at place of<br/>
residence and actual address, telephone number (work, mobile), details of<br/>
documents on education, qualification, professional training, employment<br/>
agreements, NDA agreements, information on bonuses and compensation,<br/>
information on marital status, family members, social security (or other taxpayer<br/>
identification) number, office location and other data.<br/><br/><br/>
5. Use of Data <br/><br/>
GOSWIFTPE TECHNOLOGIES PRIVATE LIMITED uses the collected data for various<br/>
purposes:<br/>
a. to provide and maintain our Service;<br/>
b. to notify you about changes to our Service;<br/>
c. to allow you to participate in interactive features of our Service when you<br/>
choose to do so;<br/>
d. to provide customer support;<br/>
e. to gather analysis or valuable information so that we can improve our Service;<br/>
f. to monitor the usage of our Service;<br/>
g. to detect, prevent and address technical issues;<br/>
h. to fulfil any other purpose for which you provide it;<br/>
i. to carry out our obligations and enforce our rights arising from any contract<br/>
sentered into between you and us, including for billing and collection;<br/>
j. to provide you with notices about your account and/or subscription, including<br/>
expiration and renewal notices, email-instructions, etc.;<br/>
k. to provide you with news, special offers and general information about other
<br/>goods, services and events which we offer that are similar to those that you have<br/>
already purchased or enquired about unless you have opted not to receive such<br/>
information;<br/>
l. in any other way we may describe when you provide the information;<br/>
m. for any other purpose with your consent.<br/>
n. for processing the transactions, including but not limited to domestic and<br/>
foreign remittances.<br/>
o. Perform the required controls and checks in accordance with money<br/>
laundering/terrorist financing and know your customer requirements under<br/>
Applicable Law, and internal control policies, and well as address other law<br/>
enforcement needs as more fully described in our Terms and Conditions.<br/><br/>
6. Retention of Data<br/><br/>
We will retain your Personal Data only for as long as is necessary for the purposes<br/>
set out in this Privacy Policy. We will retain and use your Personal Data to the<br/>
extent necessary to comply with our legal obligations (for example, if we are<br/>
required to retain your data to comply with applicable laws), resolve disputes, and<br/>
enforce our legal agreements and policies.<br/>
We will also retain Usage Data for internal analysis purposes. Usage Data is<br/>
generally retained for a shorter period, except when this data is used to<br/>
strengthen the security or to improve the functionality of our Service, or we are<br/>
legally obligated to retain this data for longer time periods.<br/><br/>
7. Transfer of Data<br/><br/>
Your information, including Personal Data, may be transferred to – and<br/>
maintained on – computers located outside of your state, province, country or<br/>
other governmental jurisdiction where the data protection laws may differ from<br/>
those of your jurisdiction.<br/>
If you are located outside India and choose to provide information to us, please<br/>
note that we transfer the data, including Personal Data, to India and process it<br/>
there.Your consent to this Privacy Policy followed by your submission of such<br/>
information represents your agreement to that transfer.<br/>
GOSWIFTPE TECHNOLOGIES PRIVATE LIMITED will take all the steps reasonably necessary<br/>
to ensure that your data is treated securely and in accordance with this Privacy<br/>
Policy and no transfer of your Personal Data will take place to an organisation or a<br/>
country unless there are adequate controls in place including the security of your<br/>
data and other personal information.<br/><br/>
8. Disclosure of Data<br/><br/>
We may disclose personal information that we collect, or you provide:<br/><br/>
8.1 Disclosure for Law Enforcement.<br/><br/>
Under certain circumstances, we may be required to disclose your Personal Data<br/>
if required to do so by law or in response to valid requests by public authorities.<br/><br/>
8.2 Business Transaction.<br/><br/>
If we or our subsidiaries are involved in a merger, acquisition or asset sale, your<br/>
Personal Data may be transferred.<br/><br/>
8.3 Other cases. We may disclose your information also:<br/><br/>
a. to our parent company, subsidiaries and affiliates;<br/>
b. to contractors, service providers, and other third parties we use to support our<br/>
business;<br/>
c. to fulfil the purpose for which you provide it;<br/>
d. to provide services on the platform;<br/>
e. for the purpose of including your company’s logo on our website;<br/>
f. for any other purpose disclosed by us when you provide the information;<br/>
g. with your consent in any other cases;<br/>
h. if we believe disclosure is necessary or appropriate to protect the rights,<br/>
property, or safety of the Company, our customers, or others.<br/><br/>
9. Security of Data<br/><br/>
The security of your data is important to us but remember that no method of<br/>
transmission over the Internet or method of electronic storage is 100% secure.<br/>
While we strive to use commercially acceptable means to protect your Personal<br/>
Data, we cannot guarantee its absolute security.<br/><br/>
10. Your Data Protection Rights Under General Data Protection Regulation(GDPR)<br/><br/>
If you are a resident of the European Union (EU) and European Economic Area(EEA),<br/>
you have certain data protection rights, covered by GDPR.<br/><br/><br/>

We aim to take reasonable steps to allow you to correct, amend, delete, or limit<br/>
the use of your Personal Data.<br/>
If you wish to be informed what Personal Data we hold about you and if you want<br/>
it to be removed from our systems, please email us at
<b>support@gocosspe.com </b><br/>
In certain circumstances, you have the following data protection rights:<br/><br/>
a. the right to access, update or to delete the information we have on you;<br/>
b. the right of rectification. You have the right to have your information rectified if<br/>
that information is inaccurate or incomplete;<br/>
c. the right to object. You have the right to object to our processing of your<br/>
Personal Data;<br/>
d. the right of restriction. You have the right to request that we restrict the<br/>
processing of your personal information;<br/>
e. the right to data portability. You have the right to be provided with a copy of<br/>
your Personal Data in a structured, machine-readable and commonly used<br/>
format;<br/>
f. the right to withdraw consent. You also have the right to withdraw your consent<br/>
at any time where we rely on your consent to process your personal information;<br/><br/>
Please note that we may ask you to verify your identity before responding to such<br/>
requests. Please note, we may not able to provide Service without some necessarydata.<br/><br/>
<br/>
You have the right to complain to a Data Protection Authority about our collection<br/>
and use of your Personal Data. For more information, please contact your local<br/>
data protection authority in the European Economic Area (EEA).<br/><br/>
11. Your Data Protection Rights under the California Privacy Protection Act<br/>
(CalOPPA)<br/><br/>
CalOPPA is the first state law in the nation to require commercial websites and<br/>
online services to post a privacy policy. The law’s reach stretches well beyond<br/>
California to require a person or company in the United States (and conceivablethe <br/>
world) that operates websites collecting personally identifiable information<br/>
from California consumers to post a conspicuous privacy policy on its website<br/>
stating exactly the information being collected and those individuals with whom<br/>
it is being shared, and to comply with this policy.<br/>
<br/>
According to CalOPPA we agree to the following:<br/>
a. users can visit our site anonymously;<br/>
b. our Privacy Policy link includes the word “Privacy”, and can easily be found on<br/>
the home page of our website;<br/>
c. users will be notified of any privacy policy changes on our Privacy Policy Page;<br/>
d. users are able to change their personal information by emailing us at<br/>
<b>support@gocrosspe.com</b>.<br/>
Our Policy on “Do Not Track” Signals:<br/>
We honour Do Not Track signals and do not track, plant cookies, or use<br/>
advertising when a Do Not Track browser mechanism is in place. Do Not Track is a<br/>
preference you can set in your web browser to inform websites that you do not<br/>
want to be tracked.<br/><br/>
You can enable or disable Do Not Track by visiting the Preferences or Settings<br/>
page of your web browser.<br/><br/>
12. Your Data Protection Rights under the California Consumer Privacy Act(CCPA)<br/><br/>
If you are a California resident, you are entitled to learn what data we collect about<br/>
you, ask to delete your data and not to sell (share) it. To exercise your data<br/>
protection rights, you can make certain requests and ask us:<br/>
12.0. What personal information we have about you. If you make this request, we<br/>
will return to you:<br/>
a. The categories of personal information we have collected about you.<br/>
b. The categories of sources from which we collect your personal information.<br/>
c. The business or commercial purpose for collecting or selling your personal<br/>
information.<br/>
d. The categories of third parties with whom we share personal information.<br/>
e. The specific pieces of personal information we have collected about you.<br/>
f. A list of categories of personal information that we have sold, along with the<br/>
category of any other company we sold it to. If we have not sold your personal<br/>
information, we will inform you of that fact.<br/>
g. A list of categories of personal information that we have disclosed for a business<br/>
purpose, along with the category of any other company we shared it with.<br/>
Please note, you are entitled to ask us to provide you with this information up to<br/>
two times in a rolling twelve-month period. When you make this request, the<br/>
information provided may be limited to the personal information we collected<br/>
about you in the previous 12 months.<br/><br/>
12.1. To delete your personal information. If you make this request, we will delete<br/>
the personal information we hold about you as of the date of your request from<br/>
our records and direct any service providers to do the same. In some cases,<br/>
deletion may be accomplished through de-identification of the information. If you<br/>
choose to delete your personal information, you may not be able to use certain<br/>
functions that require your personal information to operate.<br/><br/>
12.2. To stop selling your personal information. We don’t sell or rent your personal<br/>
information to any third parties for any purpose. We do not sell your personal<br/>
information for monetary consideration. However, under some circumstances, a<br/>
transfer of personal information to a third party, or within our family of companies,<br/>
without monetary consideration may be considered a “sale” under California law.<br/>
You are the only owner of your Personal Data and can request disclosure or<br/>
deletion at any time.<br/>
If you submit a request to stop selling your personal information,we will stop<br/>
making such transfers.<br/>
Please note, if you ask us to delete or stop selling your data, it may impact your<br/>
experience with us, and you may not be able to participate in certain programs or<br/>
membership services which require the usage of your personal information to<br/>
function. But in no circumstances, we will discriminate against you for exercising<br/>
your rights.<br/>
To exercise your California data protection rights described above, please send<br/>
your request(s) by email: <b>support@gocrosspe.com.</b><br/><br/>
Your data protection rights, described above, are covered by the CCPA, short for<br/>
the California Consumer Privacy Act. To find out more, visit the official California<br/>
Legislative Information website. The CCPA took effect on 01/01/2020.<br/><br/>
13. Service Providers<br/><br/>
We may employ third party companies and individuals to facilitate our Service<br/>
(“Service Providers”), provide Service on our behalf, perform Service-related<br/>
services or assist us in analysing how our Service is used.<br/><br/>
These third parties have access to your Personal Data only to perform these tasks<br/>
on our behalf and are obligated not to disclose or use it for any other purpose.<br/><br/>
14. Analytics<br/><br/>
We may use third-party Service Providers to monitor and analyse the use of our<br/>
Service.<br/><br/>
15. CI/CD tools<br/><br/>
We may use third-party Service Providers to automate the development process<br/>
of our Service.<br/><br/>
16. Advertising<br/><br/>
We may use third-party Service Providers to show advertisements to you to help<br/>
support and maintain our Service.<br/><br/>
17. Behavioural Remarketing<br/><br/>
We may use remarketing services to advertise on third party websites to you after<br/>
<br/>you visited our Service. We and our third-party vendors use cookies to inform,<br/>
optimise and serve ads based on your past visits to our Service.<br/><br/>
18. Payments<br/><br/>
We may provide paid products and/or services within Service. In that case, we use<br/>
third-party services for payment processing (e.g. payment processors).<br/>
We will not store or collect your payment card details. That information is<br/>
provided directly to our third-party payment processors whose use of your<br/>
personal information is governed by their Privacy Policy. These payment<br/>
processors adhere to the standards set by PCI-DSS as managed by the PCI<br/>
Security Standards Council, which is a joint effort of brands like Visa, Mastercard<br/>
,American Express and Discover. PCI-DSS requirements help ensure the secure<br/>
handling of payment information.<br/><br/>
19. Links to Other Sites<br/><br/>
Our Service may contain links to other sites that are not operated by us. If you<br/>
click a third party link, you will be directed to that third party’s site. We strongly<br/>
advise you to review the Privacy Policy of every site you visit.<br/>
We have no control over and assume no responsibility for the content, privacy<br/>
policies or practices of any third party sites or services.<br/><br/>
20. Children’s Privacy<br/><br/>
Our Services are not intended for use by children under the age of 18 (“Child” or<br/>
“Children”).<br/>
We do not knowingly collect personally identifiable information from Children<br/>
<br/>under 18. If you become aware that a Child has provided us with Personal Data<br/>
,please contact us. If we become aware that we have collected Personal Data from<br/>
Children without verification of parental consent, we take steps to remove that<br/>
information from our servers.<br/><br/>
21. Changes to This Privacy Policy<br/><br/>
We may update our Privacy Policy from time to time. We will notify you of any<br/>
changes by posting the new Privacy Policy on this page.<br/><br/>
We will let you know via email and/or a prominent notice on our Service, prior to<br/>
the change becoming effective and update “effective date” at the top of this<br/>
Privacy Policy.<br/><br/>
You are advised to review this Privacy Policy periodically for any changes. Changes<br/>
to this Privacy Policy are effective when they are posted on this page.<br/><br/>
22. Liability<br/><br/>
We are not liable to you in respect of any claims, losses, damages, expenses<br/>
(including reasonable legal fees) arising out of or in connection with the use and<br/>
/or disclosure or dissemination of the user data in accordance with this privacy<br/>
policy and any consents that you may have otherwise provided to us.<br/><br/>
23. Contact Us<br/><br/>
If you have any questions about this Privacy Policy, please contact us by email:<br/>
<b>support@gocrosspe.com</b>


</div>


      </div>
     
  )
}
